In [4]:
import numpy as np

np.random.seed(4400)

matrices = [np.random.randint(-10, 11, size=(3,3)) for _ in range(3)]

In [5]:
for i, M in enumerate(matrices, start=1):
    print(f"\nMatrix {i}:")
    print(M)
    
    try:
        M_inv = np.linalg.inv(M)
        print("\nInverse:")
        print(M_inv)
        
        print("\nVerification (M × M⁻¹):")
        print(M @ M_inv)
        
    except np.linalg.LinAlgError:
        print("\nThis matrix is not invertible (determinant = 0).")


Matrix 1:
[[-7 -3 -5]
 [-6 -7  9]
 [-7  5  4]]

Inverse:
[[-0.07135875 -0.01270772 -0.06060606]
 [-0.03812317 -0.06158358  0.09090909]
 [-0.07722385  0.05474096  0.03030303]]

Verification (M × M⁻¹):
[[ 1.00000000e+00 -2.08166817e-17 -1.11022302e-16]
 [ 3.88578059e-16  1.00000000e+00 -8.32667268e-17]
 [ 0.00000000e+00 -2.77555756e-17  1.00000000e+00]]

Matrix 2:
[[ 6 -9 -4]
 [ 9 -2 -2]
 [-4 -1 10]]

Inverse:
[[-0.03264095  0.13946588  0.0148368 ]
 [-0.12166172  0.0652819  -0.03560831]
 [-0.02522255  0.06231454  0.10237389]]

Verification (M × M⁻¹):
[[ 1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 6.93889390e-18  1.00000000e+00  0.00000000e+00]
 [-6.93889390e-18  2.77555756e-17  1.00000000e+00]]

Matrix 3:
[[-9 10 -4]
 [-4  0  3]
 [-6  0 -1]]

Inverse:
[[-0.00000000e+00 -4.54545455e-02 -1.36363636e-01]
 [ 1.00000000e-01  6.81818182e-02 -1.95454545e-01]
 [ 1.34572488e-17  2.72727273e-01 -1.81818182e-01]]

Verification (M × M⁻¹):
[[ 1.00000000e+00 -2.22044605e-16 -3.33066907e-16]
 [

Each matrix was generated randomly. NumPy's `linalg.inv` function was used to attempt
to compute the inverse. When the inverse exists, multiplying the matrix
by its inverse yields the identity matrix (up to floating-point error).
If the matrix is singular, NumPy throws an error, indicating that the
inverse does not exist.
